;This file is the display text dictionary for ContextMenuManager.
;It helps translators provide translations and submit them to Github. Replace the content to the right of the equal sign with the translated text.
;General - Translator is the translation contributor, General - Language is the language name, e.g., en-US for American English,
;General - TranslatorUrl is the URL of the translation contributor (any URL that can be opened with the Win+R command is acceptable)
;Translation notes: Leave values blank if not translated temporarily. Use \r\n or \n for line breaks in dictionary values.
;For multiple translation contributors, use \r\n or \n to separate Translator values and their corresponding TranslatorUrl values.
;If a contributor has no URL, assign null, ensuring contributors and links correspond one-to-one. Example: Translator = Bob \r\n Join \r\n Andi, 
;TranslatorUrl = https://github.com/BluePointLilac \r\n null \r\n https://gitee.com/BluePointLilac

[General]
AppName = Windows Context Menu Manager
Language = en-US English
Translator = User
TranslatorUrl = null

[ToolBar]
Home = Home
Type = File Types
Rule = Other Rules
Refresh = Refresh
About = About

[SideBar]
File = File
Folder = Folder
Directory = Directory
Background = Directory Background
Desktop = Desktop Background
Drive = Drive
AllObjects = All Objects
Computer = This PC
RecycleBin = Recycle Bin
Library = Library
New = New Menu
SendTo = Send To
OpenWith = Open With
WinX = Win+X

LnkFile = lnk File
UwpLnk = uwp lnk
ExeFile = exe File
CustomExtension = Custom Format
PerceivedType = Perceived Type
DirectoryType = Directory Type
UnknownType = Unknown Format
MenuAnalysis = Menu Analysis

EnhanceMenu = Enhance Menu
DetailedEdit = Detailed Edit
DragDrop = Drag & Drop
PublicReferences = Public References
CustomRegPath = Custom Path
GuidBlocked = GUID Blocked
IEMenu = IE Browser

AppSetting = Settings
AppLanguage = Language
CheckUpdate = Check for Updates
Dictionaries = Dictionaries
AboutApp = About
Donate = Donate

[StatusBar]
File = Context menu for all file types
Folder = Context menu for all folders
Directory = Context menu for all directories
Background = Context menu for directory and desktop backgrounds
Desktop = Desktop background context menu
Drive = Context menu for all disk drives
AllObjects = Context menu for all file system objects (including files and folders)
Computer = Context menu for the This PC icon
RecycleBin = Context menu for the Recycle Bin icon
Library = Context menu for all libraries and library directory backgrounds
New = "New" menu items in the context menu for directory and desktop backgrounds
SendTo = "Send To" menu items in the context menu for all file system objects
OpenWith = "Open With" menu items in the context menu for all files
WinX = Win+X menu items in the context menu for the "Start" button on Win8~Win10

LnkFile = Context menu for all LNK shortcuts
UwpLnk = Context menu for Win8~Win10 UWP app shortcuts
ExeFile = Context menu for all EXE executable files
CustomExtension = Context menu for custom file formats
PerceivedType = Context menu for custom file perceived types
DirectoryType = Context menu for custom directory perceived types
UnknownType = Context menu for unassociated file formats
MenuAnalysis = Analyze the location of all context menu items for a specified file object

EnhanceMenu = Add powerful and convenient menu items
DetailedEdit = Detailed settings for some internal system and program menus
DragDrop = Context menu items when dragging and dropping files
PublicReferences = Edit public reference Shell submenu items added by users
CustomRegPath = Edit custom registry path context menu items
GuidBlocked = Hide stubborn ShellEx items that rely on GUIDs
IEMenu = Internet Explorer context menu

[Menu]
ChangeText = Change Text
ItemIcon = Menu Icon
ChangeIcon = Change Icon
ShieldIcon = Shield Icon
AddIcon = Add Icon
DeleteIcon = Delete Icon
ItemPosition = Menu Position
SetDefault = Default
SetTop = Top
SetBottom = Bottom
OtherAttributes = Other Attributes
OnlyWithShift = Show only when holding Shift
OnlyInExplorer = Show only in Explorer window
NoWorkingDirectory = Do not use the right-click directory information
NeverDefault = Never use as the default left-click command
ShowAsDisabledIfHidden = Gray out when disabled instead of hiding
Details = Details
WebSearch = Web Search
ChangeCommand = Change Command
RunAsAdministrator = Run as Administrator
FileProperties = File Properties
FileLocation = File Location
RegistryLocation = Registry Location
ExportRegistry = Export Registry
Delete = Delete This Item
DeleteReference = Delete Reference
HandleGuid = Handle GUID
CopyGuid = Copy GUID
BlockGuid = Block GUID
ClsidLocation = CLSID Path
AddGuidDic = Add Dictionary
InitialData = Edit Initial Data
BeforeSeparator = Show Above Separator
ChangeGroup = Change Group
RestoreDefault = Restore Default
Edit = Edit
Save = Save
FoldAll = Fold All
UnfoldAll = Unfold All

[Dialog]
Browse = Browse
Program = Program
AllFiles = All Files
RegistryFile = Registry File
ItemText = Menu Text
ItemCommand = Menu Command
CommandArguments = Command Arguments
SingleMenu = Single-level
MultiMenu = Multi-level
Public = Public
Private = Private
SelectAll = Select All
InputGuid = Enter GUID
AddGuidDic = Add GUID Local Dictionary
DeleteGuidDic = Delete
NoPerceivedType = No Perceived Type
TextFile = Text File
DocumentFile = Document File
ImageFile = Image File
VideoFile = Video File
AudioFile = Audio File
CompressedFile = Compressed File
SystemFile = System File
DocumentDirectory = Document Directory
ImageDirectory = Image Directory
VideoDirectory = Video Directory
AudioDirectory = Audio Directory
EditSubItems = Edit Submenu Items for "%s"
DetailedEdit = Detailed Edit for "%s" Menu Items
CheckReference = Please select the menu items you want to reference
CheckCopy = Please select the menu items you want to copy
SelectExtension = Please select a file extension
SelectPerceivedType = Please select a file perceived type
SelectDirectoryType = Please select a directory perceived type
SelectGroup = Please select a group to save to
SelectNewItemType = Please select the new menu type
SelectObjectType = Please select the object type to analyze
SelectDropEffect = Please select the default drag-and-drop command
DefaultDropEffect = Default (Move in same drive, Copy across drives)
CopyDropEffect = Copy (Ctrl)
MoveDropEffect = Move (Shift)
CreateLinkDropEffect = Create Shortcut (Alt)
DownloadLanguages = Download Language Files
TranslateTool = Translation Tool
DefaultText = Default Text
OldTranslation = Old Translation
NewTranslation = New Translation
DonateInfo = This list is updated periodically. Last update: %date \r\n\r\nTotal amount: %money RMB, Total donations: %count times

[Message]
TextCannotBeEmpty = Menu text cannot be empty!
CommandCannotBeEmpty = Menu command cannot be empty!
StringParsingFailed = Localization string parsing failed!
TextLengthCannotExceed80 = Menu text is too long. Length cannot exceed 80 characters!
ConfirmDeletePermanently = Are you sure you want to permanently delete this item?\r\nThis operation cannot be undone. Please proceed with caution!
DeleteButCanRestore = Are you sure you want to delete this menu's registry item?\r\nSince automatic backup is enabled (enabled by default),\r\nyou can restore it from the backup folder after deletion.
ConfirmDeleteReference = Are you sure you want to remove the reference to this item?
ConfirmDelete = Are you sure you want to delete this item?
ConfirmDeleteReferenced = Are you sure you want to delete this item?\r\nAll items that reference this will become invalid. Please proceed with caution!
CannotAddNewItem = The system limits submenus to a maximum of 16 items.\r\nCannot add more submenu items!
VistaUnsupportedMulti = Vista does not support multi-level menus!
CannotHideSubItem = Your system version is too old and does not support hiding submenu items!
UnsupportedFilename = Unsupported file name.\r\nA menu item with the same file name may already exist!
NoOpenModeExtension = This extension has no associated default program.\r\nPlease associate a program with this file type first!
CannotChangePath = Cannot change file path!
CopiedToClipboard = Copied to clipboard:
MalformedGuid = Incorrect GUID format
HasBeenAdded = This item has already been added!
SelectSubMenuMode = This multi-level menu has 0 sub-items. You have two options:\r\n① All submenu items of this multi-level menu are private (recommended).\r\n② This multi-level menu can reference the same sub-items as other multi-level menus.\r\nPlease make your choice...
EditInitialData = This program currently only supports editing the initial data of plain text files.\r\nFor other file types, please edit the registry "Data" value yourself.\r\nDo you want to continue?
PromptIsOpenItem = This item is the "Open" menu for a file or folder.\nBlindly operating it may cause the file or folder to become unopenable.\nAre you sure you want to continue? (Not recommended)
SelectRegPath = Operation steps:\r\n① Open Registry Editor (automatically)\r\n② Navigate to the target registry path\r\n③ Close the Registry Editor window.\nAre you sure you want to continue?
RestartApp = The program will restart!
FileNotExists = File does not exist!
FolderNotExists = Folder does not exist!
UpdateInfo = [Update Check]\r\nCurrent version: %v1\r\nLatest version: %v2\r\nDownload the update now?
UpdateSucceeded = Program updated successfully!
DicUpdateSucceeded = Dictionaries and language files updated successfully!
VersionIsLatest = The current version is the latest!
WebDataReadFailed = Failed to read web data!
OpenWebUrl = Open the relevant webpage?
AuthorityProtection = This menu's registry item may be protected by security software.\r\nIt cannot be disabled, deleted, or otherwise modified.
WinXSorted = To optimize sorting, some items have been renumbered.\r\nYou need to restart File Explorer for the changes to take effect.
RestoreDefault = Restore default menu items?
DeleteGroup = Permanently delete this group and all menu items within it?

[Tip]
RestartExplorer = Restarting Explorer will cause the desktop to flicker briefly. This is normal. Don't worry.\r\nAlternatively, you can restart or log off later to apply your changes.
CustomFolder = Disabling this will also disable the Customize tab\r\nin the properties panel of file system objects.
SendToDrive = Only effective when a removable disk is inserted.\r\nDisplays all partitions of the removable disk.
BuildSendtoMenu = Disabling this will speed up the main menu opening\r\nbut will slow down the "Send To" submenu opening.
InvalidItem = Invalid menu items will cause all menu items below this one\r\nto be invisible (recommended to delete).
EditSubItems = Edit submenu items
AddReference = Add reference from public reference items
AddFromPublic = Copy menu items from public references
AddFromParentMenu = Copy items from the parent menu
AddSeparator = Add separator
DeleteGuidDic = Delete the local GUID dictionary for this item added by the user
LockNewMenu = When enabled, prevents third-party programs from adding items\r\nand allows sorting of existing items (reverts upon disabling)
DropOrSelectObject = Drag or select a file or directory using the button
ConfigPath = Changing the configuration and data file save path may\r\ncause some enabled enhanced menus to stop working.\r\nYou can re-enable them in the enhanced menu.
CommandFiles = This command depends on a configuration file. Moving the configuration file\r\nwill cause this menu item to stop working. Just re-enable it.
CreateGroup = Create a new group
ImmediatelyCheck = Check Now

[Other]
CustomFolder = Customize this folder (&F)...
BuildSendtoMenu = Quickly build "Send To" submenu
NewItem = Create a new menu item
AddGuidBlockedItem = Add GUID blocked item
LockNewMenu = Lock New menu and enable sorting
InvalidItem = Invalid menu item:
Separator = >>>>>> Separator <<<<<<
SelectRegPath = Select a registry key
CurrentExtension = The file extension you selected is %s
CurrentPerceivedType = The file perceived type you selected is %s
CurrentDirectoryType = The directory perceived type you selected is %s
CurrentFilePath = The file object path you selected is
CurrentRegPath = The registry path you selected is
WinXSortable = Enable WinX menu sorting
ShowFilePath = Display file path in the status bar in real-time
OpenMoreRegedit = Open multiple Registry Editor windows
OpenMoreExplorer = Open multiple File Explorer windows
RestartExplorer = Some operations require restarting File Explorer to take effect
SwitchDictionaries = Switch dictionaries
WebDictionaries = Web dictionaries
UserDictionaries = User dictionaries
DictionaryDescription = Dictionary description
GuidInfosDictionary = GUID Information
UwpMode = UWP Module
Translators = Translation Contributors
DonationList = Donation List
ConfigPath = Configuration and data file save location
AppDataDir = AppData Directory
AppDir = Program Directory
AutoBackup = Automatically backup the registry when deleting menus
SetUpdateFrequency = Set automatic update check frequency
OnceAWeek = Once a week
OnceAMonth = Once a month
OnceASeason = Once a season
NeverCheck = Never check
SetRequestRepo = Set network data access repository
ProtectOpenItem = Protect menu items named "Open"
WebSearchEngine = Set the search engine for web searches
CustomEngine = Custom
SetCustomEngine = Set search engine (use %s instead of the search keyword)
HideDisabledItems = Hide disabled menu items
HideSysStoreItems = Hide system menus in public references
SetPerceivedType = Set the perceived type for the %s extension to
SetDefaultDropEffect = Set the default drag-and-drop command for file objects to
TopMost = Keep window always on top

AboutApp = [Compatibility]\r\n 1 = Compatible with Win10, 8.1, 8, 7, Vista\r\n 2 = Compatible with 64-bit and 32-bit operating systems\r\n 3 = Supports high DPI displays; optimal scaling is 150%\r\n\r\n[Open Source]\r\n 1 = Language: C#, WinForms, MIT license\r\n 2 = Github Repository: https://github.com/BluePointLilac/ContextMenuManager \r\n 3 = Gitee Repository: https://gitee.com/BluePointLilac/ContextMenuManager \r\n\r\n[Important Notes]\r\n 1 = This program performs numerous read, write, and delete operations on registry keys and files. These actions are sensitive and may be\r\n mistakenly flagged as a virus by Windows Defender or other antivirus software. If this occurs, please add the program to the whitelist.\r\n\r\n 2 = Some special menu items may not appear directly in the context menu due to other factors.\r\n However, based on the general rules used by this program, they will still appear as enabled. This is normal.\r\n\r\n 3 = Different context menu managers may use different methods to disable menus. It is recommended not to use multiple context menu managers simultaneously.\r\n Most programs use a simple backup-and-delete method. This program attempts to use system-provided keys for hiding.\r\n For menu items disabled by other programs, please restore them using that program first; otherwise, they may not appear in this program.\r\n\r\n 4 = This program is not designed to clean up leftover items from uninstalled programs, but it can help you locate the registry and file paths related to menu items.\r\n You can take action based on the information provided. If you are a novice user, it is recommended to only use the enable/disable switches.

Dictionaries = [Dictionary Description]\r\n This program has several dictionary files. Each dictionary has a user dictionary (User directory) and a web dictionary (Web directory).\r\n To add a dictionary to this program, save the file to the User directory via the right-click menu and follow the instructions inside the file.\r\n You can also send your dictionary to my email or submit a merge request on Github to contribute to this project.\n The right tab contains the original dictionary content. You can switch tabs to view, right-click to edit, or save it.\r\n\r\n[Dictionary Content]\r\n 1 = Program display text language dictionary (Languages directory)\r\n 2 = ShellEx menu item GUID text and icon dictionary (GuidInfosDic.ini)\r\n 3 = Detailed settings dictionary for system and other program internal menus (DetailedEditDic.xml)\r\n 4 = Enhanced menu items dictionary (EnhanceMenusDic.xml)\r\n 5 = UWP module items dictionary (UWPModeItemsDic.xml)

Donate = This program is completely free. If you find it useful, you can support the author by scanning\r\nthe QR code below (WeChat, Alipay, Tencent QQ). Any amount is appreciated. Thank you for your support!\r\nAlso, please consider starring this project on Github or Gitee (it means a lot to me!).
